---
title: "Test2"
author: "Monica"
date: "1/27/2020"
output: html_document
---
We are going to make plots in R using the ggplot2 package from tidyverse


```{r}
library(tidyverse)
library(readxl)
library(here)
```


```{r}
ci_np<-read_excel(here("data","ci_np.xlsx"))
```


```{r}
ggplot(data = ci_np, aes(x = year, y = visitors)) +
  geom_point()
```

Make base layer for my CI plots
```{r}
gg_base <- ggplot(data = ci_np, aes(x = year, y = visitors)) 
```
- Line / point colors: color
- Change line type: linetype
- Change transparency: alpha
- Change point style: pch
```{r}
gg_base + 
  geom_point(color = "dodgerblue", pch=2, size = 10)
  

```

```{r}
gg_base + 
  geom_point(aes(size = visitors , color = year))
```


```{r}
gg_base +
  geom_area() +
  theme_dark()
```



```{r}
ggplot(data=ca_np, aes(x = year , y = visitors, group = park_name)) +
  geom_line()


```


```{r}
ggplot(data=ca_np, aes(x = year , y = visitors, group = park_name, color=park_name)) +
  geom_line()
```

```{r}
my_np_graph <- ggplot(data=ca_np, aes(x = year, y = visitors)) +
  geom_point( aes(color = park_name) , show.legend = FALSE) +
  facet_wrap(~park_name, scales = "free") +
  theme_bw()
```


```{r}
ggsave(plot = my_np_graph, here("figures", "my_np_plot.png"))
```

